accounts/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

urlpatterns = [
#    url(r'^(?P<username>\w+)/$', views.myprofileview, name="detail_profile"),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^userpage/$', views.userpage, name='userpage'),
    url(r'^first_book/$', views.first_book, name='first_book'),
    url(r'^edit_profile/$', views.update_profile, name='update_profile'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', auth_views.login,name='login',
        kwargs={'redirect_authenticated_user': True, 'template_name': 'registration/login.html'}),
    url(r'^logout/$', auth_views.logout, name='logout',
        kwargs={'next_page': 'login'}),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^change_password/$', views.change_password, name='change_password'),
]

mysite/urls.py
from django.conf.urls import include, url, handler404
from django.contrib import admin
# Static helper function only for development!
from django.conf.urls.static import static
from django.conf import settings
from accounts import views



from django.contrib.auth import views as auth_views
handler404 = 'accounts.views.index'


urlpatterns = [

   
	url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

    url(r'^(?P<username>[-\w.]+)/$', views.myprofileview, name="myprofileview"),
    url(r'^$', views.index, name="indexview"),
    
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
	url(r'^avatar/', include('avatar.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from image_cropping import ImageCropField, ImageRatioField
from sorl.thumbnail import ImageField
from urllib.request import urlopen, HTTPError
from django.template.defaultfilters import slugify

from django.core.files.base import ContentFile

class Profile(models.Model):
    """
    Define model for user profile with one-to-one relationship with User table.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=20, blank=True)
    country = CountryField(blank=True)
    about = models.TextField(max_length=1000, blank=True)
    facebook = models.CharField(max_length=500, blank=True)
    instagram = models.CharField(max_length=20, blank=True)
    twitter = models.CharField(max_length=20, blank=True)
    file = ImageField(upload_to='uploaded_images', blank=True )
    firstbook = ImageField(upload_to='uploaded_images', blank=True)
    bookname = models.CharField(max_length=200, blank=True)
    bookgenre = models.CharField(max_length=200, blank=True)
    bookurl = models.CharField(max_length=500, blank=True)
    secondbook = ImageField(upload_to='uploaded_images', blank=True)

# Define signals to update user profile whenever we create/update User model.

    @property
    def photo_url(self, default_path="/static/assets/img/faces/face-0.jpg"):
        if self.file and hasattr(self.file, 'url'):
            return self.file.url 
         
        return default_path

    
        
    @property
    def firstbook_url(self, default_path="/static/assets/img/background/bookcover.png"):
        if self.firstbook and hasattr(self.firstbook, 'url'):
            return self.firstbook.url
         
        return default_path


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """
    Create Profile object whenever new User object is created.

    """
    instance.username = instance.username.lower()
    if created:
        Profile.objects.create(user=instance)
import pdb
"""def save_profile(backend, user, response, *args, **kwargs):
     
    if backend.name == 'facebook':
        #"http://graph.facebook.com/%s/picture?type=large" % response['id']
        #print (user)
        email = response['email']
        user = User.objects.filter(email=email)

        first_name = response.get('first_name')
        last_name = response.get('last_name')
        email = response.get('email')"""
def save_profile(backend, user, response, *args, **kwargs):
    #pdb.set_trace()
    
    if user:
        if kwargs['is_new']:
            attrs = {'user': user}
            if backend.name == 'facebook':
                print("new user")
                profile = Profile.objects.get(user = user)
                url = "http://graph.facebook.com/%s/picture?type=large" % response['id']
                avatar = urlopen(url)
                user.profile.file.save(slugify(user.username + " social") + '.jpg', 
                        ContentFile(avatar.read()))                
                user.profile.facebook = response.get('link')
                user.profile.facebook = user.profile.facebook[25:]
                user.profile.save()
            if backend.name == 'google-oauth2':
                print("new user")
                profile = Profile.objects.get(user = user)
                if response.get('image') and response['image'].get('url'):
                    url = response['image'].get('url')
                    url = url.replace("?sz=50","?sz=200")
                    avatar = urlopen(url)
                    user.profile.file.save(slugify(user.username + " social") + '.jpg', 
                        ContentFile(avatar.read())) 
                user.first_name = response['name']['givenName']
                user.last_name = response['name']['familyName']
                user.email = response['emails'][0]['value']
                user.profile.save()

        else:
            print("old user")
            profile = Profile.objects.get(user = user)
            if backend.name == 'facebook':
                #pdb.set_trace()
                if not user.profile.file:
                    url = "http://graph.facebook.com/%s/picture?type=large" % response['id']
                    avatar = urlopen(url)
                    user.profile.file.save(slugify(user.username + " social") + '.jpg', 
                        ContentFile(avatar.read()))
                if not user.profile.facebook:
                    user.profile.facebook = response['link']
                    user.profile.facebook = user.profile.facebook[25:]
                user.profile.save()
                


            if backend.name == 'google-oauth2':
                print("google user")
                if not user.profile.file:
                    if response.get('image') and response['image'].get('url'):
                        url = response['image'].get('url')
                        url = url.replace("?sz=50","?sz=200")
                        avatar = urlopen(url)
                        user.profile.file.save(slugify(user.username + " social") + '.jpg', 
                            ContentFile(avatar.read()))
                #pdb.set_trace()

            user.profile.save()
        """profile = Profile.objects.get(user=user)
        #if not profile.file:
        url = "http://graph.facebook.com/%s/picture?type=large" % response['id']
        avatar = urlopen(url)
        profile.file.save(slugify(user.username + " social") + '.jpg', 
                        ContentFile(avatar.read())) 
        #if not profile.facebook:  
        profile.facebook = response['link']
        profile.facebook = profile.facebook[25:]
        profile.about = response['email']
        profile.save()"""       

        
            

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    """
    Update Profile object whenever new User object is updated.
    """

    instance.profile.save()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from .models import Profile
from django.core.files import File
from PIL import Image
from django.forms.widgets import FileInput







class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200)

    def clean_email(self):
        email = self.cleaned_data['email'].strip()
        try:
            User.objects.get(email__iexact=email)
            raise forms.ValidationError('email already exists')
        except User.DoesNotExist:
            return email

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')



    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        #if self.fields['username'].error_messages is not None:
        #    attrs['class'] = 'errors'
        self.fields['username'].label = ''
        self.fields['username'].widget.attrs={
            'class':'form-control border-input',
            #'readonly': True
            }

        self.fields['email'].label = ''
        self.fields['email'].widget.attrs={
            'class':'form-control border-input',
            #'readonly': True
            }
        self.fields['first_name'].required = True
        self.fields['first_name'].widget.attrs={
            'class':'form-control border-input',

            }
        self.fields['last_name'].required = True
        self.fields['last_name'].widget.attrs={
            'class':'form-control border-input',

            }

class EditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','email')

    def __init__(self, *args, **kwargs):
        super(EditForm, self).__init__(*args, **kwargs)
        #if self.fields['username'].error_messages is not None:
        #    attrs['class'] = 'errors'
        self.fields['username'].label = ''
        self.fields['username'].widget.attrs={
            'class':'form-control border-input',
            #'readonly': True
            }

        self.fields['email'].label = ''
        self.fields['email'].widget.attrs={
            'class':'form-control border-input',
            #'readonly': True
            }

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('facebook','instagram','twitter','country', 'about',)
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        
        
        self.fields['facebook'].widget.attrs={
            'class':'form-control border-input',
            'placeholder': 'username',
            }

        
        self.fields['instagram'].widget.attrs={
            'class':'form-control border-input',
            'placeholder': 'username',
            }

        
        self.fields['twitter'].widget.attrs={
            'class':'form-control border-input',
            'placeholder': 'username',
            }

        self.fields['about'].required = True
        self.fields['about'].widget.attrs={
            'class':'form-control border-input',
            'placeholder': 'Something about you... ',
            'rows':'5',
            'minlength':'200',
	    'maxlength':'1000',

            }

        self.fields['country'].required = True
        self.fields['country'].widget.attrs={
            'class':'form-control',
            #'style':'max-width:90%;',
            
            
            }

class BookFieldsForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bookname','bookgenre','bookurl',)
    def __init__(self, *args, **kwargs):
        super(BookFieldsForm, self).__init__(*args, **kwargs)
        
        self.fields['bookname'].required = True
        self.fields['bookname'].widget.attrs={
            'class':'form-control border-input',
            }

        self.fields['bookgenre'].required = True
        self.fields['bookgenre'].widget.attrs={
            'class':'form-control border-input',
            }

        

class PhotoForm(forms.ModelForm):
    file = forms.ImageField(widget=forms.FileInput)
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    class Meta:
        model = Profile
        fields = ('file', 'x', 'y', 'width', 'height',)
    widgets = {
        'file': forms.FileInput,
    }
    def __init__(self, *args, **kwargs):
        super(PhotoForm, self).__init__(*args, **kwargs)
        self.fields['file'].label = ''
        self.fields['file'].widget.attrs={
            'class':'upload',

            #'style': 'display:none;',
            }

    def save(self):
        profile = super(PhotoForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(profile.file)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(profile.file.path)

        return profile

class PhotoForm1(forms.ModelForm):
    file1 = forms.ImageField(widget=forms.FileInput)
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    class Meta:
        model = Profile
        fields = ('file1', 'x', 'y', 'width', 'height',)
    
    def __init__(self, *args, **kwargs):
        super(PhotoForm1, self).__init__(*args, **kwargs)
        self.fields['file1'].label = ''
        self.fields['file1'].widget.attrs={
            'class':'upload',

            #'style': 'display:none;',
            }

    def save(self):
        profile = super(PhotoForm1, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(profile.file)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(profile.file1.path)

        return profile

class FirstBookForm(forms.ModelForm):
    firstbook = forms.ImageField(widget=forms.FileInput)
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    class Meta:
        model = Profile
        fields = ('firstbook', 'x', 'y', 'width', 'height',)
    widgets = {
        'firstbook': forms.FileInput,
    }
    def __init__(self, *args, **kwargs):
        super(FirstBookForm, self).__init__(*args, **kwargs)
        self.fields['firstbook'].label = ''
        self.fields['firstbook'].widget.attrs={
            'class':'upload',

            #'style': 'display:none;',
            }

    def save(self):
        profile = super(FirstBookForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(profile.firstbook)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((210, 280), Image.ANTIALIAS)
        resized_image.save(profile.firstbook.path)

        return profile

class PasswordChangeForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ('password',)
        

templates/accounts/activation_completed.html
{% extends 'registration/login.html' %}

{% block javascript %}
<script> demo.showSwal('email-verified'); </script>
{% endblock %}

templates/accounts/activation_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

templates/accounts/first_book.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'assets/img/favicon.png' %}">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<link rel="icon" type="image/png" href="{% static "assets/img/favicon.png"%}">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta name="description" content="Create your free, homepage in just a few minutes.">
<meta name="author" content="Jugadi Time">
<meta name="keywords" content="thepoet.me, thepoet, thepoetdotme, poets, poetme, thepoetme">
<title>thepoet.me | your personal identity page</title>

<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
<meta name="viewport" content="width=device-width" />


<!-- Bootstrap core CSS     -->
<link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />

<!--  Paper Dashboard core CSS    -->
<link href="{% static 'assets/css/paper-dashboard.css' %}" rel="stylesheet"/>


<!--  CSS for Demo Purpose, don't include it in your project     -->
<link href="{% static 'assets/css/demo.css' %}" rel="stylesheet" />
<link href="{% static 'assets/css/cropper.min.css' %}" rel="stylesheet">



<!--  Fonts and icons     -->
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
<link href="{% static 'assets/css/themify-icons.css' %}" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-transparent navbar-absolute">
<div class="container">
<div class="navbar-header">
<button type="button" class="navbar-toggle navbar-toggle-black" data-toggle="collapse" data-target="#navigation-example-2">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar "></span>
<span class="icon-bar "></span>
<span class="icon-bar"></span>
</button>
 <a class="navbar-brand" href="{% url 'userpage' %}">thepoet.me</a>
</div>
<div class="collapse navbar-collapse">
<ul class="nav navbar-nav navbar-right">
<li>
<a href="{% url 'view_profile' %}" class="btn">
Back to profile
</a>
</li>
</ul>
</div>
</div>
</nav>

<div class="wrapper wrapper-full-page">
<div class="full-page login-page" data-color="green" >

<!--   you can change the color of the filter page using: data-color="blue | azure | green | orange | red | purple" -->


<div class="content">
<div class="container-fluid">
<div class="row">

<div class="col-md-8 col-md-offset-2">
<div class="card-header">
<h4 class="card-title">Edit Profile</h4>
</div>

<div class="card card-user">
<div class="author"> 
<div class="card-content">
<div class="row">
<div class="col-md-4">
<img  src="{{ request.user.profile.firstbook_url }}" alt="..."/>
<div class="overlay"></div>
<small><form  method="post" enctype="multipart/form-data" id="formUpload">
{% csrf_token %}
<div class="fileUpload btn btn-primary btn-simple">
{{ form }}
<span>Change Book Cover</span>
</div>
</form> </small>
</div>

{% if request.user.profile.firstbook %}
<div class="col-md-8">  
<form method="post" id="allInputsFormValidation" enctype="multipart/form-data">
{% csrf_token %}                   
<div class="form-group">
<label>Book Name</label>
{{ book_fields_form.bookname }}
</div>
</div>

<div class="col-md-8">
<div class="form-group">
<label>Book Genre</label>
{{ book_fields_form.bookgenre }}
</div>
</div>


<div class="col-md-8">
<div class="form-group">
<label>Link to Buy</label>
<input type="url" name="bookurl" value='{{ book_fields_form.bookurl.value }}' id="id_bookurl" class="form-control border-input" placeholder="https://" required="">
</div>        
</div>


<div class="text-center">
{% if request.user.profile.bookname %}
<button type="submit" class="btn btn-info btn-fill btn-wd">Update Details</button>

{% else %}

<button type="submit" class="btn btn-info btn-fill btn-wd">Add Details</button>
</div>

{% endif %}
{% else %}
<div class="col-md-8">

<div class="alert alert-warning alert-with-icon" data-notify="container">

<span data-notify="icon" class="ti-lock"></span>
<span data-notify="message">You have to upload cover picture first to fill other fields.</span>
</div>


</div>


{% endif %}
</div>
</div>
<hr>


</div>
</div>
</div>
</div>
</div>
</div>

<div class="container">
<div class="modal fade" id="modalCrop">
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-label="Close">
<span aria-hidden="true">&times;</span>
</button>
<h4 class="modal-title">Crop the photo</h4>
</div>
<div class="modal-body">
<img src="" id="image" style="max-width: 100%;">
</div>
<div class="modal-footer">
<div class="btn-group pull-left" role="group">
<button type="button" class="btn btn-default js-zoom-in">
<span class="ti-plus"></span>
</button>
<button type="button" class="btn btn-default js-zoom-out">
<span class="ti-minus"></span>
</button>
</div>
<button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
<button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
</div>
</div>
</div>
</div>
</div>



<footer class="footer footer-transparent">
<div class="container">
<div class="copyright text-center">
&copy; <script>document.write(new Date().getFullYear())</script>, Developed by <a href="https://jugaditi.me">Jugadi Time</a>
& Designed by <a href="https://www.creative-tim.com/">Creative Tim</a>
</div>
</div>
</footer>
</div>
</div>
</body>


<!--   Core JS Files. Extra: TouchPunch for touch library inside jquery-ui.min.js' %}   -->
<script src="{% static 'assets/js/jquery-3.1.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/jquery-ui.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/perfect-scrollbar.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>

<!--  Forms Validations Plugin -->
<script src="{% static 'assets/js/jquery.validate.min.js' %}"></script>

<!-- Promise Library for SweetAlert2 working on IE -->
<script src="{% static 'assets/js/es6-promise-auto.min.js' %}"></script>

<!--  Plugin for Date Time Picker and Full Calendar Plugin-->
<script src="{% static 'assets/js/moment.min.js' %}"></script>

<!--  Date Time Picker Plugin is included in this js file -->
<script src="{% static 'assets/js/bootstrap-datetimepicker.js' %}"></script>

<!--  Select Picker Plugin -->
<script src="{% static 'assets/js/bootstrap-selectpicker.js' %}"></script>

<!--  Switch and Tags Input Plugins -->
<script src="{% static 'assets/js/bootstrap-switch-tags.js' %}"></script>

<!-- Circle Percentage-chart -->
<script src="{% static 'assets/js/jquery.easypiechart.min.js' %}"></script>

<!--  Charts Plugin -->
<script src="{% static 'assets/js/chartist.min.js' %}"></script>

<!--  Notifications Plugin    -->
<script src="{% static 'assets/js/bootstrap-notify.js' %}"></script>

<!-- Sweet Alert 2 plugin -->
<script src="{% static 'assets/js/sweetalert2.js' %}"></script>

<!-- Vector Map plugin -->
<script src="{% static 'assets/js/jquery-jvectormap.js' %}"></script>

<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

<!-- Wizard Plugin    -->
<script src="{% static 'assets/js/jquery.bootstrap.wizard.min.js' %}"></script>

<!--  Bootstrap Table Plugin    -->
<script src="{% static 'assets/js/bootstrap-table.js' %}"></script>

<!--  Plugin for DataTables.net  -->
<script src="{% static 'assets/js/jquery.datatables.js' %}"></script>

<!--  Full Calendar Plugin    -->
<script src="{% static 'assets/js/fullcalendar.min.js' %}"></script>

<!-- Paper Dashboard PRO Core javascript and methods for Demo purpose -->
<script src="{% static 'assets/js/paper-dashboard.js' %}"></script>
<script src="{% static 'assets/js/cropper.min.js' %}"></script>

<script>
$(function () {

		/* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
		$("#id_firstbook").change(function () {
				if (this.files && this.files[0]) {
				var reader = new FileReader();
				reader.onload = function (e) {
				$("#image").attr("src", e.target.result);
				$("#modalCrop").modal("show");
				}
				reader.readAsDataURL(this.files[0]);
				}
				});

		/* SCRIPTS TO HANDLE THE CROPPER BOX */
		var $image = $("#image");
		var cropBoxData;
		var canvasData;
		$("#modalCrop").on("shown.bs.modal", function () {
				$image.cropper({
viewMode: 1,
aspectRatio: 3/4,
minCropBoxWidth: 210,
minCropBoxHeight: 280,
ready: function () {
$image.cropper("setCanvasData", canvasData);
$image.cropper("setCropBoxData", cropBoxData);
}
});
				}).on("hidden.bs.modal", function () {
					cropBoxData = $image.cropper("getCropBoxData");
					canvasData = $image.cropper("getCanvasData");
					$image.cropper("destroy");
					});

$(".js-zoom-in").click(function () {
		$image.cropper("zoom", 0.1);
		});

$(".js-zoom-out").click(function () {
		$image.cropper("zoom", -0.1);
		});

/* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
$(".js-crop-and-upload").click(function () {
		var cropData = $image.cropper("getData");
		$("#id_x").val(cropData["x"]);
		$("#id_y").val(cropData["y"]);
		$("#id_height").val(cropData["height"]);
		$("#id_width").val(cropData["width"]);
		$("#formUpload").submit();
		});

});
</script>




<!-- Paper Dashboard PRO DEMO methods, don't include it in your project! -->
<script src="{% static 'assets/js/demo.js' %}"></script>
{% block javascript %}
{% endblock %}
<script type="text/javascript">
$().ready(function(){
		demo.checkFullPageBackgroundImage();

		setTimeout(function(){
				// after 1000 ms we add the class animated to the login/register card
				$('.card').removeClass('card-hidden');
				}, 700)
		});
</script>

</html>